# Generated by Django 4.2.15 on 2024-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0003_user_delete_company_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
