# Generated by Django 4.2.15 on 2024-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siparis",
            name="description",
            field=models.TextField(max_length=10000),
        ),
    ]
