# Generated by Django 4.2.15 on 2024-08-24 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Vidasan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiparisActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("pressAmount", models.IntegerField(blank=True, null=True)),
                ("pressOutputKg", models.FloatField(blank=True, null=True)),
                ("pressWastageKg", models.FloatField(blank=True, null=True)),
                ("pressStartDateTime", models.DateTimeField(blank=True, null=True)),
                ("byckAmount", models.IntegerField(blank=True, null=True)),
                ("byckOutputKg", models.FloatField(blank=True, null=True)),
                ("byckWastageKg", models.FloatField(blank=True, null=True)),
                ("byckStartDateTime", models.DateTimeField(blank=True, null=True)),
                ("ovalamaAmount", models.IntegerField(blank=True, null=True)),
                ("ovalamaOutputKg", models.FloatField(blank=True, null=True)),
                ("ovalamaWastageKg", models.FloatField(blank=True, null=True)),
                ("ovalamaStartDateTime", models.DateTimeField(blank=True, null=True)),
                ("sementasyonAmount", models.IntegerField(blank=True, null=True)),
                ("sementasyonOutputKg", models.FloatField(blank=True, null=True)),
                ("sementasyonWastageKg", models.FloatField(blank=True, null=True)),
                (
                    "sementasyonStartDateTime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("kaplamaAmount", models.IntegerField(blank=True, null=True)),
                ("kaplamaOutputKg", models.FloatField(blank=True, null=True)),
                ("kaplamaWastageKg", models.FloatField(blank=True, null=True)),
                ("kaplamaStartDateTime", models.DateTimeField(blank=True, null=True)),
                ("ambalajAmount", models.IntegerField(blank=True, null=True)),
                ("ambalajOutputKg", models.FloatField(blank=True, null=True)),
                ("ambalajWastageKg", models.FloatField(blank=True, null=True)),
                ("ambalajStartDateTime", models.DateTimeField(blank=True, null=True)),
                (
                    "ambalajMachine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_ambalaj",
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "ambalajOperator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_ambalaj",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "byckMachine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_byck",
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "byckOperator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_byck",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kaplamaMachine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_kaplama",
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "kaplamaOperator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_kaplama",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ovalamaMachine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_ovalama",
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "ovalamaOperator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_ovalama",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pressMachine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_press",
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "pressOperator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_press",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sementasyonMachine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_sementasyon",
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "sementasyonOperator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparis_activity_by_sementasyon",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "siparis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="Vidasan.siparis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
