# Generated by Django 4.2.15 on 2024-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0002_alter_siparis_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siparis",
            old_name="isOem",
            new_name="isOEM",
        ),
        migrations.AddField(
            model_name="siparis",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siparis",
            name="state",
            field=models.CharField(
                choices=[
                    ("Isıl İşlem", "Isil Islem"),
                    ("Kaplama", "Kaplama"),
                    ("Ovalama", "Ovalama"),
                    ("Patch", "Patch"),
                    ("Planlama", "Planlama"),
                    ("Press", "Press"),
                    ("Sipariş Tamamlandı", "Siparis Tamamlandi"),
                ],
                default="Planlama",
                max_length=300,
            ),
        ),
    ]
