# Generated by Django 4.2.15 on 2024-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0002_siparisactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="siparisactivity",
            name="ambalajEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siparisactivity",
            name="byckEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siparisactivity",
            name="kaplamaEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siparisactivity",
            name="ovalamaEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siparisactivity",
            name="pressEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siparisactivity",
            name="sementasyonEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
