# Generated by Django 4.2.15 on 2024-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0003_rename_isoem_siparis_isoem_siparis_isactive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siparis",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
