# Generated by Django 4.2.15 on 2024-08-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Vidasan",
            "0004_rename_ambalajenddatetime_siparisactivity_ambalajfinishdatetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="variation",
            field=models.CharField(
                choices=[
                    ("CH3", "Ch3"),
                    ("CH5", "Ch5"),
                    ("CH5L", "Ch5L"),
                    ("CH5S", "Ch5S"),
                    ("CH6", "Ch6"),
                ],
                max_length=100,
            ),
        ),
    ]
