# Generated by Django 4.2.15 on 2024-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0006_alter_siparis_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.CharField(
                choices=[
                    ("kaplama", "Kaplama"),
                    ("ovalama", "Ovalama"),
                    ("press", "Press"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="variation",
            field=models.CharField(
                choices=[
                    ("CH3", "Ch3"),
                    ("CH5", "Ch5"),
                    ("CH5L", "Ch5L"),
                    ("CH5S", "Ch5S"),
                    ("CH6", "Ch6"),
                    ("Kaplama Tedarikcisi", "Kaplama Tedarikcisi"),
                ],
                max_length=100,
            ),
        ),
    ]
