# Generated by Django 4.2.15 on 2024-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0008_siparis_orderdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siparis",
            name="state",
        ),
        migrations.AddField(
            model_name="siparis",
            name="ambalajState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siparis",
            name="byckState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siparis",
            name="kaplamaState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siparis",
            name="ovalamaState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siparis",
            name="pressState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siparis",
            name="sementasyonState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="kaplama",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Çinko Kaplama", "Cinkokaplama"),
                    ("Çinko Nikel Şeffaf Kaplama", "Cinkonikelseffafkaplama"),
                    ("Çinko Nikel Siyah Kaplama", "Cinkonikelsiyahkaplama"),
                    ("Çinko Siyah Kaplama", "Cinkosiyahkaplama"),
                    ("Geomet Kaplama", "Geometkaplama"),
                    ("Janjan Kaplama", "Janjankaplama"),
                    ("Nikel Kaplama", "Nikel"),
                    ("Sarı Kaplama", "Sarikaplama"),
                ],
                default="",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="material",
            field=models.CharField(
                choices=[
                    ("CQ15", "Cq15"),
                    ("Direct Çekim", "Directcekim"),
                    ("SAE100GC", "Sae100Gc"),
                    ("15B2", " 15B2"),
                    ("20MnB4", " 20Mnb4"),
                    ("23MnB4", " 23Mnb4"),
                    ("304Cu(Paslanmaz)", " 304Cu"),
                ],
                default="20MnB4",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="orderNumber",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
