# Generated by Django 4.2.15 on 2024-08-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0009_remove_siparis_state_siparis_ambalajstate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siparis",
            name="ambalajState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                    ("Hacky", "Hacky"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="byckState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                    ("Hacky", "Hacky"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="kaplamaState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                    ("Hacky", "Hacky"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="ovalamaState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                    ("Hacky", "Hacky"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="pressState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                    ("Hacky", "Hacky"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siparis",
            name="sementasyonState",
            field=models.CharField(
                choices=[
                    ("Başlamadı", "Baslamadi"),
                    ("Beklemede", "Beklemede"),
                    ("Bitti", "Bitti"),
                    ("Çalışıyor", "Calisiyor"),
                    ("Hacky", "Hacky"),
                ],
                default="Başlamadı",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="MachineActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "fromState",
                    models.CharField(
                        choices=[
                            ("Başlamadı", "Baslamadi"),
                            ("Beklemede", "Beklemede"),
                            ("Bitti", "Bitti"),
                            ("Çalışıyor", "Calisiyor"),
                            ("Hacky", "Hacky"),
                        ],
                        default="Hacky",
                        max_length=100,
                    ),
                ),
                (
                    "toState",
                    models.CharField(
                        choices=[
                            ("Başlamadı", "Baslamadi"),
                            ("Beklemede", "Beklemede"),
                            ("Bitti", "Bitti"),
                            ("Çalışıyor", "Calisiyor"),
                            ("Hacky", "Hacky"),
                        ],
                        default="Hacky",
                        max_length=100,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Vidasan.machine",
                    ),
                ),
                (
                    "siparis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Vidasan.siparis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
