# Generated by Django 4.2.15 on 2024-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0011_siparis_state"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MachineActivity",
            new_name="SiparisLog",
        ),
    ]
