# Generated by Django 4.2.15 on 2024-08-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vidasan", "0012_rename_machineactivity_siparislog"),
    ]

    operations = [
        migrations.AddField(
            model_name="siparislog",
            name="processType",
            field=models.CharField(
                choices=[
                    ("ambalaj", "Ambalaj"),
                    ("byck", "Byck"),
                    ("kaplama", "Kaplama"),
                    ("ovalama", "Ovalama"),
                    ("press", "Press"),
                    ("sementasyon", "Sementasyon"),
                ],
                default="press",
                max_length=100,
            ),
        ),
    ]
